### ISSUE TITLE
Change.License MPL2 and change to Mission Control Center React Browser Plugin.

### ISSUE THREAD

**Issue by kabuki-starship** [a-startup/astartup.toolkit#8]
# Target Market

## Problem

I don't know how your GitHub workflow works and might not trust the product unless it's open-source and they can customize it and ensure there is no malware.

## Solution

We are now the Astartup Mission Control Center, a customizable GitHub app framework and Format for Startup Syndication (FSS). Our IMUL note scanner is now closed-source with a private server option. Now we can work on the MCC on the Astartup Live-stream and get people to pay me money (because I'm broke and have a lot of college debt) to customize their Astartup Mission Control Center.

## Hierarchy

* Flat

**Comment by CookingWithCale** [comment]
#IssueBump Change.License MPL2 and change to Mission Control Center React Browser Plugin

## Problem

I don't know how your GitHub workflow works and might not trust the product unless it's open-source and they can customize it and ensure there is no malware.

## Solution

We are now the Astartup Mission Control Center, a customizable GitHub app framework and Format for Startup Syndication (FSS). Our IMUL note scanner is now closed-source with a private server option. Now we can work on the MCC on the Astartup Live-stream and get people to pay me money (because I'm broke and have a lot of college debt) to customize their Astartup Mission Control Center.

## Hierarchy

* Flat
